# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0012_auto_20150911_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='comicstrip',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
